### ISSUE TITLE
After terraform apply - What next ? OUTER_ALB_DNS_NAME its leading to Welcome to nginx page 

### ISSUE THREAD

**Issue by highCardX** [magenx/Magento-2-aws-cluster-terraform#14]
First of all 
Thanks for your repo (magenx / Magento-2-aws-cluster-terraform) and you helping us to give an alternative of Magento Cloud Commerce.
Definitely your AWS Auto scale setup will save a lot of money.

Question : 

I followed your guide after 

-    sudo yum install -y yum-utils
-    sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
-    sudo yum -y install terraform
-    mkdir magento && cd magento
-    git clone https://github.com/magenx/Magento-2-aws-cluster-terraform.git .
(Using my own domain and did all email verification i.e. AWS Domain Certificate verification via email)
-    terraform init
-    terraform apply

what would be the next steps ?

After finding OUTER_ALB_DNS_NAME URL its leading to Welcome to nginx page 
and if I using 
OUTER_ALB_DNS_NAME/ADMIN_PATH - Its leading to 404 page 

Am I missing something ?
Do I need to run composer on admin EC2 cluster ? 

Please help

<img width="546" alt="Screenshot 2021-12-30 at 7 27 18 PM" src="https://user-images.githubusercontent.com/66768338/147759165-5bd51c5e-b23c-4a1f-a426-5d1e0e10d6b4.png">
<img width="325" alt="Screenshot 2021-12-30 at 7 27 41 PM" src="https://user-images.githubusercontent.com/66768338/147759160-dfd7056c-e0d8-4362-91f3-7e3cd26d3c20.png">
.

**Comment by magenx** [comment]
please connect to instance and check syslog for errors related to 
`nginx `
 `git `
`permissions`

also this configuration is just an example, and you can adjust it for your needs.

you have to make sure that you have full access rights in your aws account, 
all permissions for required services enabled for your user.

you can check other branches, like [fastly](../tree/fastly)
