### ISSUE TITLE
Packer fails due to instance_metadata_tags

### ISSUE THREAD

**Issue by youanden** [magenx/Magento-2-aws-cluster-terraform#20]
```
Error: Unsupported argument

  on packer.pkr.hcl line 55:
  (source code not available)

An argument named "instance_metadata_tags" is not expected here.
```
Not sure what to do in this case, because instance_metadata_tags is critical to the instances to support the user script that uses the tags for initializing variables to properly build the AMI...

Looks like the amazon plugin for packer doesn't support it yet:

https://github.com/hashicorp/packer-plugin-amazon/issues/205

You'd need to build it yourself to use it...

**Comment by magenx** [comment]
probably move it back to launch template will be better

**Comment by magenx** [comment]
also good idea to rewrite to imagebuilder to move completely to aws

**Comment by youanden** [comment]
@magenx I might make a PR for that, then.

**Comment by magenx** [comment]
imagebuilder branch created [fastly_v4_imagebuilder](../tree/fastly_v4_imagebuilder)
