### ISSUE TITLE
Codebuild install fails because iam user doesn't have kms permissions

### ISSUE THREAD

**Issue by youanden** [magenx/Magento-2-aws-cluster-terraform#21]
Because kms is enabled by default on all the buckets, including media, the iam user for media doesn't have permissions to write to the bucket. 

I think we should probably just disable encryption for the media folder given that it is private by default anyways and requires valid ACL. 

I've updated the rule like so:
```
resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
  for_each = var.s3
  bucket   = "${local.project}-${random_string.s3[each.key].id}-${each.key}"
  rule {
    dynamic "apply_server_side_encryption_by_default" {
      for_each = each.key != "media" ? [1] : []
      content {
        kms_master_key_id = "aws/s3"
        sse_algorithm     = "aws:kms"
      }
    }
  }
}
```

The problem also happens with the backup bucket when the install codepipeline runs the last step, since the IAM role doesn't have access to kms either.

**Comment by magenx** [comment]
reverted back to S3 default server side encryption
