### ISSUE TITLE
Codebuild install fails due to lz4 missing in codebuild container

### ISSUE THREAD

**Issue by youanden** [magenx/Magento-2-aws-cluster-terraform#24]
I've traced an issue in the codepipeline install when configuring redis cache/session. The errors are fairly generic, and now I understand are related to the fact that codebuild doesn't have php-lz4 installed, which causes the commands to fail in codebuild for things like config and compilation. 

Perhaps we run some sed commands to enable the compression after build is complete before commits are done? I couldn't find a straightforward way to install lz4 or any other php extension in codebuild without compiling from source or getting php from another repo.

**Comment by magenx** [comment]
this issue can be fixed with options

compile lz4, its fast

```
      - php -v
      - php -m
      - cd /tmp
      - git clone --recursive --depth=1 https://github.com/kjdev/php-ext-lz4.git
      - cd php-ext-lz4
      - phpize
      - ./configure
      - make
      - make install
      - echo 'extension="/root/.phpenv/versions/${PHP_74_VERSION}/lib/php/extensions/no-debug-non-zts-20190902/lz4.so"' > /root/.phpenv/versions/${PHP_74_VERSION}/etc/conf.d/lz4.ini
      - php -m

```

or build custom image, 
ps. they dont have 8.1 runtime builds
