### ISSUE TITLE
Nginx issues

### ISSUE THREAD

**Issue by youanden** [magenx/Magento-2-aws-cluster-terraform#25]
The nginx user doesn't have access to read the /var/run/php/php7.4-fpm.sock file. setfacl has allowed nginx access to read the web root, but not the php socket.

Also, a constant seems to have not been replaced in nginx configuration:
nginx: [emerg] host not found in "INSTANCE_LOCAL_IP:80" of the "listen" directive in /etc/nginx/sites-enabled/magento.conf:5

I've replaced with:
```
listen 80;
```

**Comment by magenx** [comment]
fixed this issue
must be working now
