### ISSUE TITLE
Invalid imagebuilder policy

### ISSUE THREAD

**Issue by youanden** [magenx/Magento-2-aws-cluster-terraform#28]
![CleanShot 2022-04-02 at 16 55 01](https://user-images.githubusercontent.com/183880/161400922-cd80c734-96b7-45e1-b88d-bfcf18632776.png)

The system s3 bucket policy in `fastly_v4_imagebuilder` does not save because the new statement with Principal AWS "*" overrides the current user's permissions (or so it seems). You can try updating in the GUI and see that S3 will not accept this statement and will return 403.

For now I have replaced the statement to:
```
{
  Action = ["s3:PutObject"],
  Effect = "Allow"
  Resource = "${aws_s3_bucket.this["system"].arn}/imagebuilder/*"
  Principal = {
    AWS = [
      aws_iam_role.ec2["frontend"].arn,
      aws_iam_role.ec2["admin"].arn
    ]
  }
}
```

Which is then enough for imagebuilder to write the component artifacts.

**Comment by magenx** [comment]
it is fixed now
while not sure about role or instance profile
