### ISSUE TITLE
Imagebuilder variable declarations missing (needed to access to parameterstore to create a valid AMI)

### ISSUE THREAD

**Issue by youanden** [magenx/Magento-2-aws-cluster-terraform#29]
The `imagebuilder/build.yml` file references `PARAMETERSTORE_NAME` which isn't defined anywhere. Same for `INSTANCE_NAME`

I suggest making the following modifications.

build.yml:
```
_AWSTOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 60")
PARAMETERSTORE_NAME=$(curl -s -H "X-aws-ec2-metadata-token: ${_AWSTOKEN}" http://169.254.169.254/latest/meta-data/tags/instance/Project)-env
_INSTANCE_NAME=$(curl -s -H "X-aws-ec2-metadata-token: ${_AWSTOKEN}" http://169.254.169.254/latest/meta-data/tags/instance/InstanceName)
```
(changes in the file referencing the name without the `_`)

imagebuilder.tf:
```
resource_tags = {
  Resource = "${local.project}-${each.key}-image"
  Project = "${local.project}"
  InstanceName = "${each.key}"
}
```
(using InstanceName instead of Name because it's reserved in resource_tags)

The launch templates already include the Project tag, so this would just ensure that the Build/Test EC2 instances include it for proper builds.

**Comment by magenx** [comment]
#30
