### ISSUE TITLE
Magento2 dependencies are missing

### ISSUE THREAD

**Issue by safoorsafdar** [magenx/Magento-2-aws-cluster-terraform#3]
Hi, thank you for your work. 
I am facing below mentioned issue:

root@server:/home/mgtx2f1/public_html# su mgtx2f1 -s /bin/bash -c "bin/magento module:enable --all"
PHP Warning:  require(/home/mgtx2f1/public_html/vendor/composer/../smile/elasticsuite/src/module-elasticsuite-catalog-graph-ql/registration.php): failed to open stream: No such file or directory in /home/mgtx2f1/public_html/vendor/composer/autoload_real.php on line 73
PHP Fatal error:  require(): Failed opening required '/home/mgtx2f1/public_html/vendor/composer/../smile/elasticsuite/src/module-elasticsuite-catalog-graph-ql/registration.php' (include_path='/home/mgtx2f1/public_html/vendor/magento/zendframework1/library:.:/usr/share/php') in /home/mgtx2f1/public_html/vendor/composer/autoload_real.php on line 73
root@server:/home/mgtx2f1/public_html# ls -lah vendor/smile/elasticsuite/src/
total 112K
drwxrws---+ 14 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 .
drwxrws---+  3 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 ..
drwxrws---+  3 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 lib
drwxrws---+  4 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 module-elasticsuite-admin-notification
drwxrws---+  9 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 module-elasticsuite-analytics
drwxrws---+ 14 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 module-elasticsuite-catalog
drwxrws---+ 13 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 module-elasticsuite-catalog-optimizer
drwxrws---+  9 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 module-elasticsuite-catalog-rule
drwxrws---+ 18 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 module-elasticsuite-core
drwxrws---+  9 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 module-elasticsuite-indices
drwxrws---+  8 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 module-elasticsuite-swatches
drwxrws---+ 14 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 module-elasticsuite-thesaurus
drwxrws---+ 14 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 module-elasticsuite-tracker
drwxrws---+ 15 mgtx2f1 php-mgtx2f1 4.0K Aug 26 11:06 module-elasticsuite-virtual-category

as per the composer.lock file, it should be present in the package folder.
![image](https://user-images.githubusercontent.com/5680768/130961298-3b91e315-988e-44e2-80d7-270c18a905cd.png)

**Comment by magenx** [comment]
this is related to our [magento-2](https://github.com/magenx/Magento-2/tree/aws) repository, we have removed #https://github.com/Smile-SA/elasticsuite/issues/2238 module, because for base package it has too many hardcoded dependencies.
