### ISSUE TITLE
Imagebuilder Dynamic aws_launch_template reference

### ISSUE THREAD

**Issue by youanden** [magenx/Magento-2-aws-cluster-terraform#31]
We should probably implement a dynamic image_id for aws image builder:
ec2_autoscaling.tf [here](https://github.com/magenx/Magento-2-aws-cluster-terraform/blob/d219c7a9dc441277a321057ddde88c2b60e0cf82/ec2_autoscaling.tf#L117):
```
image_id      = tolist(aws_imagebuilder_image.this[each.key].output_resources.0.amis).0.image
```

**Comment by magenx** [comment]
yes this is required 
just need to set proper type
