### ISSUE TITLE
Git version < 2.28 doesn't support `-b`

### ISSUE THREAD

**Issue by youanden** [magenx/Magento-2-aws-cluster-terraform#33]
Because of this, user_data fails to initialize the code repository correctly with:
```
error: unknown switch `b'
```

With ubuntu, this is as simple as:
```
add-apt-repository ppa:git-core/ppa -y
apt-get -qqy install ${parameter["LINUX_PACKAGES"]}
```

Alternatively, user_data can be updated to:
```
git init
git symbolic-ref HEAD refs/heads/main
```

Without any build changes.

**Comment by magenx** [comment]
but debian 11 arm git version is 2.30 ?
is there any environment changes?

**Comment by youanden** [comment]
@magenx I switched to Ubuntu myself, so I guess this is only affecting Ubuntu-based builds.

**Comment by magenx** [comment]
sure,
but then this will be related to specific environment
