### ISSUE TITLE
Error: Missing resource instance key

### ISSUE THREAD

**Issue by inmediape** [magenx/Magento-2-aws-cluster-terraform#34]
Error: Missing resource instance key
│ 
│   on codepipeline.tf line 213, in resource "aws_iam_policy" "codepipeline":
│  213:                         "Resource": aws_codestarconnections_connection.github.arn,
│ 
│ Because aws_codestarconnections_connection.github has "for_each" set, its attributes must be accessed on specific instances.
│ 
│ For example, to correlate with indices of a referring resource, use:
│     aws_codestarconnections_connection.github[each.key]

**Comment by magenx** [comment]
please remove for_each from `aws_codestarconnections_connection` resource
