### ISSUE TITLE
Enhancement requirest for Connect with Key Pair

### ISSUE THREAD

**Issue by selcuk-cofe** [magenx/Magento-2-aws-cluster-terraform#6]
Hi again, 

it would be great if you can add support to connect instances with pre-existing or new key pair as plus to session manager.

**Comment by magenx** [comment]
aws recommends to use ssm manager with iam policies to manage secure access,
you can use ssm manager to deploy ssh keys and reconfigure ssh

**Comment by selcuk-cofe** [comment]
Thanks , will use that way.
